#!/bin/bash

# Code to execute simulations with different log-normal distributions for cluster growth without fragmentation.
# This code requires a file created by causes_of_asynchrony_1oct2024.R with the parameters of the doubling time distributions
# for the simulations
# Inputs:
#   -n: Number of simulations to be executed for each doubling time distribution combination (line in the csv file)
#   -m: Maximum cluster size (number of cells the clusters are allowed to have)
#   -i: input file, csv file generated by causes_of_asynchrony_1oct2024.R with the information of the doubling time distributions
#   -t: Number of threads/parallel processes to use

while getopts "n:m:i:t:p:" option
do
case "${option}"
in
n) sim_number=${OPTARG};;
m) max_clust_size=${OPTARG};;
i) input_file=${OPTARG};;
t) num_threads=${OPTARG};;
p) death_prob=${OPTARG};;
*) echo "Invalid option or missing option argument for -$OPTARG" >&2; exit 1;;
esac
done

echo "Starting simulations with parameters:"
echo "Number of simulations per parameter set: ${sim_number}"
echo "Maximum cluster size: ${max_clust_size}"
echo "Input file: ${input_file}"
echo "Number of parallel threads: ${num_threads}"
echo "========================================"

# Function to execute a single simulation
run_simulation() {
    local delay_level=$1
    local var_level=$2
    local log_mean1=$3
    local log_std1=$4
    local log_mean2=$5
    local log_std2=$6
    local sim_number=$7
    local max_clust_size=$8
    local death_prob=$9
    
    # Create output directory name
    output_dir="test_${var_level}_var_${delay_level}_diff"
    
    # Construct the command
    cmd="sim_clust_no_fragmentation_lognormal_death_prob_5aug2025.py -n ${sim_number} -o ${output_dir} -m ${max_clust_size} -i ${log_mean1},${log_std1} -j ${log_mean2},${log_std2} -p ${death_prob}"
    
    # Execute the command
    echo "Executing: $cmd"
    eval $cmd
    
    # Check if the command was successful
    if [ $? -eq 0 ]; then
        echo "Command executed successfully for delay_level=${delay_level}, var_level=${var_level}"
    else
        echo "Error: Command failed for delay_level=${delay_level}, var_level=${var_level}"
    fi
    
    echo "----------------------------------------"
}

# Export the function and variables so they're available to parallel processes
export -f run_simulation
export sim_number
export max_clust_size
export death_prob

# Create a temporary file to store the CSV data (excluding header)
temp_file=$(mktemp)
tail -n +2 ${input_file} > ${temp_file}

# Use GNU parallel for execution
echo "Using GNU parallel for execution..."
parallel -j ${num_threads} --colsep ',' run_simulation {1} {2} {5} {6} {9} {10} ${sim_number} ${max_clust_size} ${death_prob} :::: ${temp_file}

# Clean up temporary file
rm ${temp_file}

echo "All commands have been executed."