#!/bin/bash

# Code to execute simulations with different log-normal distributions for several cluster generations selecting one cluster after 
#fragmentation to continue growing.
# This code requires a file created by fast_first_div_7july2025.R with the parameters of the doubling time distributions
#for the simulations
# Inputs:
#   -n: Number of simulations to be executed for each doubling time distribution combination (line in the csv file)
#   -g: number of cluster generations to be simulated
#   -u: minimum edge degree threshold value for fragmentation
#   -x: maximum edge degree threshold value for fragmentation
#   -c: cluster to keep after fragmentation. Options: random, parent, propagule
#   -i: input file, csv file generated by fast_first_div_7july2025.R with the information of the doubling time distributions

while getopts "n:g:u:x:c:i:" option
do
case "${option}"
in
n) sim_number=${OPTARG};;
g) generations=${OPTARG};;
u) min_edge_degree=${OPTARG};;
x) max_edge_degree=${OPTARG};;
c) cluster_to_keep=${OPTARG};;
i) input_file=${OPTARG};;
*) echo "Invalid option or missing option argument for -$OPTARG" >&2; exit 1;;
esac
done

# Check if the CSV file exists
if [ ! -f ${input_file} ]; then
    echo "Error: CSV file not found!"
    exit 1
fi

# Skip the header line and process each row of the CSV file
tail -n +2 ${input_file} | while IFS=',' read -r delay_level var_level col3 col4 log_mean1 log_std1 col7 col8 log_mean2 log_std2 col11
do
    # Loop through edge degree threshold values
    for degree_cont in $(seq ${min_edge_degree} ${max_edge_degree})
    do
        # Construct the command
        cmd="sim_frag_clust_diff_mean_dists_24apr2024.py -n ${sim_number} -o test_${var_level}_var_${delay_level}_diff_${degree_cont}_deg -g ${generations} -e ${degree_cont} -i ${log_mean1},${log_std1} -j ${log_mean2},${log_std2} -c ${cluster_to_keep}"
        
        # Execute the command
        echo "Executing: $cmd"
        eval $cmd
        
        # Check if the command was successful
        if [ $? -eq 0 ]; then
            echo "Command executed successfully."
        else
            echo "Error: Command failed."
        fi
        
        echo "----------------------------------------"
    done
done

echo "All commands have been executed."