#!/bin/bash

# Code to execute simulations with different log-normal distributions for cluster growth without fragmentation.
# This code requires a file created by causes_of_asynchrony_1oct2024.R with the parameters of the doubling time distributions
# for the simulations
# Inputs:
#   -n: Number of simulations to be executed for each doubling time distribution combination (line in the csv file)
#   -m: Maximum cluster size (number of cells the clusters are allowed to have)
#   -i: input file, csv file generated by causes_of_asynchrony_1oct2024.R with the information of the doubling time distributions

while getopts "n:m:i:" option
do
case "${option}"
in
n) sim_number=${OPTARG};;
m) max_clust_size=${OPTARG};;
i) input_file=${OPTARG};;
*) echo "Invalid option or missing option argument for -$OPTARG" >&2; exit 1;;
esac
done

# Check if required arguments are provided
if [ -z "$sim_number" ] || [ -z "$max_clust_size" ] || [ -z "$input_file" ]; then
    echo "Error: Missing required arguments!"
    echo "Usage: $0 -n <number_of_simulations> -m <max_cluster_size> -i <input_csv_file>"
    exit 1
fi

# Check if the CSV file exists
if [ ! -f ${input_file} ]; then
    echo "Error: CSV file not found!"
    exit 1
fi

echo "Starting simulations with parameters:"
echo "Number of simulations per parameter set: ${sim_number}"
echo "Maximum cluster size: ${max_clust_size}"
echo "Input file: ${input_file}"
echo "========================================"

# Skip the header line and process each row of the CSV file
tail -n +2 ${input_file} | while IFS=',' read -r delay_level var_level col3 col4 log_mean1 log_std1 col7 col8 log_mean2 log_std2 col11
do
    # Create output directory name
    output_dir="test_${var_level}_var_${delay_level}_diff"
    
    # Construct the command
    cmd="sim_clust_no_fragmentation_fast_first_div_7july2025.py -n ${sim_number} -o ${output_dir} -m ${max_clust_size} -i ${log_mean1},${log_std1} -j ${log_mean2},${log_std2}"
    
    # Execute the command
    echo "Executing: $cmd"
    eval $cmd
    
    # Check if the command was successful
    if [ $? -eq 0 ]; then
        echo "Command executed successfully for delay_level=${delay_level}, var_level=${var_level}"
    else
        echo "Error: Command failed for delay_level=${delay_level}, var_level=${var_level}"
    fi
    
    echo "----------------------------------------"
done

echo "All commands have been executed."